apiVersion: v1
kind: Service
metadata:
  name: {{ include "fider.fullname" . }}
  labels:
    {{- include "fider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  - name: http-metrics
    port: 4000
    protocol: TCP
  selector:
    {{- include "fider.selectorLabels" . | nindent 4 }}
